name: Build macOS

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install Ruby
        run: brew install ruby

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GENERATOR }}
        run: github_changelog_generator -u NoobTaco -p gomacdeploy

      - name: Build
        run: go build -o gomacdeploy -v ./...

      - name: Copy config.yaml
        run: cp config.yaml ./gomacdeploy

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false