name: Build macOS

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Install git-chglog
      run: brew tap git-chglog/git-chglog && brew install git-chglog

    - name: Generate changelog
      run: git-chglog -o CHANGELOG.md

    - name: Build
      run: go build -o gomacdeploy -v ./...

    - name: Copy config.yaml
      run: cp config.yaml ./gomacdeploy

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          ./gomacdeploy
          ./config.yaml
          ./CHANGELOG.md