name: goreleaser

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      # - name: '✏️ Generate release changelog'
      #   uses: janheinrichmerker/action-github-changelog-generator@v2.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        builds:
          - main: ./cmd/main.go
            goos: darwin
            goarch:
              - amd64
              - arm64
            ldflags: -s -w
            env:
              - CGO_ENABLED=0
            extra_files:
              - src: ./config.yaml
                dest: config.yaml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
